yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls)
]

handler403 = 'core.views.forbidden'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return self.text[:15]

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.pk})

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
        default='')
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        return f'{self.user} FOLLOWS {self.author}'

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

        constraints = [
            models.CheckConstraint(
                check=~models.Q(author=models.F('user')),
                name='no_self_subscribe'
            ),

            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_subscribing'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

        labels = {
            'text': 'Текст',
            'group': 'Группа',
            'image': 'Картинка'
        }

        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа для поста',
            'image': 'Картинка для поста',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

        labels = {
            'text': 'Текст',
        }

        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import cache_clear, paginator


def index(request):
    post_list = Post.objects.all()
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator(post_list, request)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)

    post_list = user.posts.all()
    page_obj = paginator(post_list, request)

    if request.user.is_authenticated and Follow.objects.filter(
            user=request.user,
            author=user
    ).exists():
        following = True
    else:
        following = False

    context = {
        'author': user,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if request.user != post.author:
        return redirect(post)

    if form.is_valid():
        post = form.save()
        return redirect(post)

    return render(request, 'posts/create_post.html', {
        'form': form,
    })


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    page_obj = {}
    if Follow.objects.filter(user=user).exists():
        follows = user.follower.all()
        followed_authors = User.objects.filter(following__in=follows)
        post_list = Post.objects.filter(author__in=followed_authors)
        page_obj = paginator(post_list, request)
        context = {
            'page_obj': page_obj
        }
    else:
        context = {
            'page_obj': page_obj
        }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists() is False:
        Follow.objects.create(
            user=request.user,
            author=author
        )
        cache_clear('follow_index_page_cache', request.user)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user,
        author = get_object_or_404(User, username=username)
    ).delete()

    cache_clear('follow_index_page_cache', request.user)
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}



{% block title%}
{% with request.resolver_match.view_name as view_name %}

{% if view_name == 'posts:post_create'%}
  Новый пост
{% elif view_name == 'posts:post_edit' %}
  Редактировать пост
{% endif %}

{% endwith %}
{% endblock%}     


{% block content %}
{% with request.resolver_match.view_name as view_name %}

{% if view_name == 'posts:post_create'%}
  {% include 'includes/user_interface_form.html' with card_title='Новый пост' card_button='Сохранить' %}
{% elif view_name == 'posts:post_edit' %}
  {% include 'includes/user_interface_form.html' with card_title='Редактировать пост' card_button='Добавить' %}
{% endif %}

{% endwith %}
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
  Ваши подписки
{% endblock %}

{% block content %}
<h1> Ваши подписки </h1>
{% include 'posts/includes/switcher.html' %}


{% load cache %}  
{% cache 20 follow_index_page_cache request.user.username with page_obj %}

  {% for post in page_obj %}
    {% include 'includes/post.html' %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% empty %}
    Подписок нет!
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}
{% endcache %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title%}
  Записи сообщества {{ group.title }}
{% endblock%}

{% block content %}
<h1>{{group.title}}</h1>
<p>
  {{group.description}}
</p>   
  {% for post in page_obj %} 
    {% include 'includes/post.html' %}   
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  
  {% include 'posts/includes/paginator.html' %}  
  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
<h1> Последние обновления на сайте </h1>
{% include 'posts/includes/switcher.html' %}

{% load cache %}
{% cache 20 index_page_cache with page_obj %}

  {% for post in page_obj %}
    {% include 'includes/post.html' %} 
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}



  {% include 'posts/includes/paginator.html' %}
{% endcache %}


{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %} 
Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
              {% if post.group %}   
              <li class="list-group-item">   
                Группа: {{ post.group }}
                <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
              {% endif %}
              </li>
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my sc-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|linebreaks }}
          </p>
            {% if user == post.author %}
              <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
                редактировать запись
              </a>
            {% endif %}                 
        
            <!-- Форма добавления комментария -->
            {% load user_filters %}

            {% if user.is_authenticated %}
              <div class="card my-4">
                <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body">
                  <form method="post" action="{% url 'posts:add_comment' post.id %}">
                    {% csrf_token %}      
                    <div class="form-group mb-2">
                      {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                  </form>
                </div>
              </div>
            {% endif %}

            {% for comment in comments %}
              <div class="media mb-4">
                <div class="media-body">
                  <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                      {{ comment.author.username }}
                    </a>
                  </h5>
                    <p>
                    {{ comment.text }}
                    </p>
                  </div>
                </div>
            {% endfor %}
          </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}

{% block content %}

<div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
    {% if request.user != author %}
        {% if following %}
            <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
                Отписаться
            </a>
        {% else %}
            <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
                Подписаться
            </a>
        {% endif %}
    {% endif %}
</div>

{% for post in page_obj %} 
    {% include 'includes/post.html' %}   
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}  

{% include 'posts/includes/paginator.html' %}
    
{% endblock %}